AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Genera il repository maven e include gli stack di generazione dei CodeBuild project per 
  effettuare il build di librerie, microservizi e webapp.

Parameters:
  PnCiCdTemplatesBucketName:
    Type: String
    Description: Bucket name where pipeline copied the current version of CI templates
  CodeArtifactDomainName:
    Type: String
    Default: pn-codeartifact-domain
  CodeArtifactRepositoryName:
    Type: String
    Default: pn-codeartifact-repo
  NotificationSNSTopic:
    Type: String
    Default: 'none'
    Description: Topic for build and pipeline notification
  
  AllowedDeployAccount1:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount2:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount3:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount4:
    Type: Number
    Description: Account number allowed to read the artifacts
  AllowedDeployAccount5:
    Type: Number
    Description: Account number allowed to read the artifacts


Resources:
  CodeArtifactStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/infra/code-artifact.yaml'
      Parameters:
        CodeArtifactDomainName: !Ref 'CodeArtifactDomainName'
        CodeArtifactRepositoryName: !Ref 'CodeArtifactRepositoryName'
      TimeoutInMinutes: 5

  
  :
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
  
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CiArtifactBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${CiArtifactBucket}
              - !Sub arn:aws:s3:::${CiArtifactBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AllowedDeployAccount1}:root
                - !Sub arn:aws:iam::${AllowedDeployAccount2}:root
                - !Sub arn:aws:iam::${AllowedDeployAccount3}:root
                - !Sub arn:aws:iam::${AllowedDeployAccount4}:root
                - !Sub arn:aws:iam::${AllowedDeployAccount5}:root


Outputs:
  CiArtifactBucket:
    Value: !Ref 'CiArtifactBucket'
